[general]
fontname=DejaVu Sans Mono 16
selchars=-A-Za-z0-9,./?%&#:_
scrollback=1000
bgcolor=rgb(10,14,30)
fgcolor=rgb(235,235,235)
hidescrollbar=true
hidemenubar=true
hideclosebutton=true
disablef10=true
disablealt=true
